name: Build for PCs

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build_msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Install SDL2
      run: vcpkg install sdl2:x86-windows sdl2:x64-windows

    - run: |
        mkdir build
        cmake -E make_directory build/Win32
        cmake -E make_directory build/x64

    - name: Configure CMake
      working-directory: build
      run: |
        pushd Win32
        cmake ../.. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
        popd
        pushd x64
        cmake ../.. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
        popd

    - name: Build
      working-directory: build
      run: |
        cmake --build Win32 --config %BUILD_TYPE%
        cmake --build x64 --config %BUILD_TYPE%
    
    - name: Check dirs (temporary)
      run: |
        dir
        dir /S build/Win32
        dir /S build/x64
